# Sample of a configuration. Copy this file and edit it. Set the environment variable `NOZZLE_CONFIG`
# to its location. See the CONFIG.md for more context.
# 
# Note that using a config file is not mandatory. You can alternatively provide some or all values
# through env vars. See the 'Using env vars' section of CONFIG.md for how to do this.
#
# When using filesystem paths, any relative paths will be resolved from the directory of this file.

# Where the extracted datasets are stored.
data_dir = "/config/data"

# Path to a providers directory. Each provider is configured as a separate toml file in this
# directory. Dataset definitions will reference providers by a relative path to this directory.
providers_dir = "/config/providers"

# Path to a directory containing dataset definition files.
dataset_defs_dir = "/config/dataset_defs"

# Connection to the metadata DB. Optional and experimental.
#metadata_db_url = "postgres://<pg_url>"

# How much memory the server can use in MB. Setting this to 0 means unlimited
max_mem_mb = 0

# Paths where DataFusion can create temporary files. Setting this to an
# empty array disables spill-to-disk
spill_location = []
