# The network for this endpoint. Follow the 'CLI name' in this table:
# https://thegraph.com/docs/en/developing/supported-networks/
network = "mainnet"

# The EVM RPC endpoint
url = "http://192.168.0.24:8545"